baseURL = "https://rellyson.github.io"
defaultContentLanguage = "pt"
languageCode = "pt-br"
theme = "anubis2"
title = "rellyson.github.io"
enableEmoji = true
enableGitInfo = true

[params]
dateFormat = "01/02/2006"
paginationSinglePost = true
rssAsSocialIcon = false
colorTheme = "auto"
colorThemeSwitcher = true
copyCodeButton = true
locale = "pt-br"
math = false
toc = true

social = [
    { id = "github", url = "https://github.com/rellyson" },
    { id = "linkedin", url = "https://www.linkedin.com/in/rellysonsilva" },
]

customCSS = ["custom-css/stylesheet.scss"]

[params.meta]
favicon = true

[params.author]
name = "Rellyson Silva"
location = "Belo Horizonte/MG"

[pagination]
pagerSize = 5

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'github-dark'
